---
- name: debian pre openvas tasks
  import_tasks: debian_pre_openvas.yml
  tags:
    - debian_client

- name: rhel pre openvas tasks
  import_tasks: rhel_pre_openvas.yml
  tags:
    - rhel_client

- name: include linux debian client tasks
  import_tasks: velociraptor_client_debian.yml
  tags:
    - debian_client

- name: include linux rhel client tasks
  import_tasks: velociraptor_client_rhel.yml
  tags:
    - rhel_client

- name: include velociraptor_server tasks
  import_tasks: velociraptor_server.yml
  tags:
    - server

- name: include closing openvas tasks
  import_tasks: finishing-openvas.yml
  tags:
    - server

- name: include openvas tasks
  import_tasks: openvas.yml
  tags:
    - server