---
- include: linux_client.yml
  when: client == true and ansible_os_family != "Windows"

- include: windows_client.yml
  when: client == true and ansible_os_family == "Windows"

- include: server.yml
  when: server == true