---
# tasks file for RedHat.yml

# Setup the required repositories
# yum install epel-release
- name: (RedHat) Add EPEL repository
  tags: [ 'ps::install' ]
  yum:
    name: epel-release
    state: present

- name: (RedHat) Add CRB repository
  tags: [ 'ps::install' ]
  command: dnf config-manager --set-enabled crb
  when: ansible_distribution_major_version is version('9', '>=')

# yum install dnf -y install "http://software.internet2.edu/rpms/el${OS_MAJOR}/${OS_ARCH}/latest/packages/perfsonar-repo-${PS_REPO_VERSION}.noarch.rpm"

- name: (RedHat) Get perfSONAR repository URL
  tags: [ 'ps::install' ]
  set_fact:
    perfsonar_repo_url: "http://software.internet2.edu/rpms/el{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/latest/packages/perfsonar-repo-{{ perfsonar_current_repo_version }}.noarch.rpm"

- name: (RedHat) Display perfSONAR repository URL
  tags: [ 'ps::install' ]
  debug:
    msg: "perfSONAR repository URL: {{ perfsonar_repo_url }}"

- name: (RedHat) Add perfSONAR repository
  tags: [ 'ps::install' ]
  dnf:
    name: "{{ perfsonar_repo_url }}"
    disable_gpg_check: yes
    state: present

# Install the perfSONAR bundle
- name: (RedHat) Use perfSONAR staging or nightly repository
  tags: [ 'ps::install' ]
  yum:
    name: perfSONAR-repo-{{ perfsonar_release }}
    state: present
  when:
    - perfsonar_release != "release"

# Make sure we have the latest upgrades installed
- name: (RedHat) Install system updates
  tags: [ 'ps::install' ]
  yum:
    name: '*'
    state: latest
    update_cache: yes
  ignore_errors: True
  when: perfsonar_os_update == True
