services:
  testpoint:
    container_name: perfsonar-testpoint
    image: perfsonar/testpoint:systemd
    build:
      context: .
      dockerfile: systemd/Dockerfile
    cgroup: host
    environment:
      - TZ=UTC
    network_mode: "host"
    restart: on-failure
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./compose/psconfig:/etc/perfsonar/psconfig
    tty: true