---
- name: dnf update upgrade
  include_tasks: dnf-update-upgrade.yml

- name: install common packages
  include_tasks: common-installs.yml

# Get some useful info out of the system
- name: Check system status
  include_tasks: sysinfo.yml

- name: Ensure Docker is installed
  include_tasks: install_docker.yml
  when: ansible_os_family == 'RedHat'
