---
# Get some useful info out of the system
- name: Check system status
  include_tasks: sysinfo.yml

- name: Ensure Docker is installed
  include_tasks: install_docker.yml
  when: ansible_os_family == 'RedHat'
