[hosts]

[hosts:children]
ir_headnode
linux
windows
web

[ir_headnode]

[web]

[linux:children]
debian_based
rhel_based

[linux:vars]
ansible_become=True
ansible_become_user=root
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3

# example: host3 ansible_host=192.168.220.12 ansible_user=admin
[debian_based]
practicelinux-6 ansible_host=10.100.100.78 ansible_user=root
practicelinux-4 ansible_host=10.100.100.76 ansible_user=root
practicelinux-1 ansible_host=10.100.100.77 ansible_user=root
practicelinux-3 ansible_host=10.100.100.75 ansible_user=root

[rhel_based]
practicelinux-2 ansible_host=10.100.100.73 ansible_user=root
practicelinux-5 ansible_host=10.100.100.74 ansible_user=root

[windows]

[windows:children]
windows_server

[windows:vars]
ansible_become=True
ansible_become_user=Administrator
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[windows_server]

